package ensf480.model;
import java.util.ArrayList;

//represents the Periodic Report generated by a manager and the info it holds
public class PeriodicReport {
    //fields
    private int numHousesListed;
    private int numHousesRented;
    private int numActiveListings;
    private ArrayList<Property> rentedHouses;

    //constructor
    public PeriodicReport() {
        numHousesListed = 0;
        numHousesRented = 0;
        numActiveListings = 0;
        rentedHouses = new ArrayList<>();
    }

    //constructor (for convenience)
    public PeriodicReport(int numHousesListed, int numHousesRented, int numActiveListings, ArrayList<Property> rentedHouses) {
        this.numHousesListed = numHousesListed;
        this.numHousesRented = numHousesRented;
        this.numActiveListings = numActiveListings;
        this.rentedHouses = rentedHouses;
    }
    
    //getters and setters
    public int getNumHousesListed() {
        return this.numHousesListed;
    }

    public void setNumHousesListed(int numHousesListed) {
        this.numHousesListed = numHousesListed;
    }

    public int getNumHousesRented() {
        return this.numHousesRented;
    }

    public void setNumHousesRented(int numHousesRented) {
        this.numHousesRented = numHousesRented;
    }

    public int getNumActiveListings() {
        return this.numActiveListings;
    }

    public void setNumActiveListings(int numActiveListings) {
        this.numActiveListings = numActiveListings;
    }

    public ArrayList<Property> getRentedHouses() {
        return this.rentedHouses;
    }

    public void setRentedHouses(ArrayList<Property> rentedHouses) {
        this.rentedHouses = rentedHouses;
    }


    @Override
    public String toString() {
        return "{" +
            " numHousesListed='" + getNumHousesListed() + "'" +
            ", numHousesRented='" + getNumHousesRented() + "'" +
            ", numActiveListings='" + getNumActiveListings() + "'" +
            ", rentedHouses='" + getRentedHouses() + "'" +
            "}";
    }

}
